baseURL = 'https://vinr.tech/'
languageCode = 'en-us'
title = 'vinr'
theme = "vinr-tailwind-theme"
themesDir = '../..'

enableRobotsTXT = true

defaultContentLanguage = 'en'
[languages]
[languages.en]
contentDir = 'content/en'
languageName = "English"
weight = 1
[languages.de]
contentDir = 'content/de'
languageName = "Deutsch"
weight = 2

[params]
primaryColorScheme = "indigo"
cta = "/register/"

[params.social]
facebook = "https://facebook.com/yourprofile"
instagram = "https://instagram.com/yourprofile"
twitter = "https://twitter.com/yourprofile"
github = "https://github.com/yourprofile"
youtube = "https://youtube.com/yourchannel"

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About us'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 30

[[menus.main]]
name = 'Docs'
pageRef = '/docs'
weight = 40

[[menus.footer]]
name = 'Super feature'
pageRef = '/landing/super-feature'
weight = 10

[[menus.footer]]
name = 'Terms'
pageRef = '/terms'
weight = 20

[[menus.footer]]
name = 'Privacy policy'
pageRef = '/privacy-policy'
weight = 30
