baseURL = 'https://vinr.tech/'
languageCode = 'en-us'
title = 'vinr Home'

enableRobotsTXT = true

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = "English"
    weight = 1
  [languages.de]
  contentDir = 'content/de'
    languageName = "Deutsch"
    weight = 2

[params]
  primaryColorScheme = "indigo"

[params.social]
  facebook = "https://facebook.com/yourprofile"
  instagram = "https://instagram.com/yourprofile"
  twitter = "https://twitter.com/yourprofile"
  github = "https://github.com/yourprofile"
  youtube = "https://youtube.com/yourchannel"

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20

[[menus.main]]
name = 'Docs'
pageRef = '/docs'
weight = 30

[[menus.footer]]
name = 'Terms'
pageRef = '/terms'
weight = 10

[[menus.footer]]
name = 'Privacy'
pageRef = '/privacy'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
