name = 'vinr tailwind theme'
license = 'MIT'
licenselink = 'https://github.com/vinr-eu/vinr-tailwind-theme/LICENSE'
description = 'Tailwind theme for Hugo by vinr'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/vinr-eu/vinr-tailwind-theme'

# If you have a running demo of the theme
demosite = 'https://github.com/vinr-eu/vinr-tailwind-theme'

# Taxonomy terms
tags = ['blog', 'company']
features = ['tailwind', 'responsive', 'dark mode']

# If the theme has a single author
[author]
  name = 'Richy Kalingarayar'
  homepage = 'https://www.linkedin.com/in/richy-kalingarayar-844a1170/'
